name: PSScriptAnalyzer Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze_scripts:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PowerShell
        uses: microsoft/powershell@v2

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck

      - name: Run PSScriptAnalyzer
        run: Invoke-ScriptAnalyzer -Path .\*.ps1 -SettingsPath .\PSScriptAnalyzerSettings.psd1
