name: PSScriptAnalyzer Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze_scripts:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
        with:
          # Specify the version of PowerShell you want to use.
          # For example, '7.1.3', '7', or 'latest'.
          pwsh-version: 'latest'
          
      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck

      - name: Run PSScriptAnalyzer
        run: Invoke-ScriptAnalyzer -Path .\*.ps1 -SettingsPath .\PSScriptAnalyzerSettings.psd1
