name: PSScriptAnalyzer Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze_scripts:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download and install PowerShell Core
        run: |
          $url = 'https://github.com/PowerShell/PowerShell/releases/latest/download/PowerShell-Preview.win-x64.msi'
          $path = "$env:TEMP\PowerShell-Preview.win-x64.msi"
          Invoke-WebRequest -Uri $url -OutFile $path
          Start-Process -FilePath $path -ArgumentList "/quiet" -Wait

      - name: Run PSScriptAnalyzer
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
          Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck
          Invoke-ScriptAnalyzer -Path .\*.ps1 -SettingsPath .\PSScriptAnalyzerSettings.psd1
