name: PSScriptAnalyzer

on:
  push:
    paths:
      - '**/*.ps1'

jobs:
  PSScriptAnalyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser -Repository PSGallery

      - name: Run PSScriptAnalyzer
        run: |
          $scriptPaths = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter '*.ps1' | ForEach-Object { $_.FullName }
          Invoke-ScriptAnalyzer -Path $scriptPaths -SettingsPath .github/PSScriptAnalyzerSettings.yaml
